# Project: 2两数相加
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 2两数相加.o
LINKOBJ  = 2两数相加.o
LIBS     = -L"E:/dev-c++/Dev-Cpp/MinGW64/lib" -L"E:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/dev-c++/Dev-Cpp/MinGW64/include" -I"E:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/dev-c++/Dev-Cpp/MinGW64/include" -I"E:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 2两数相加.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

2两数相加.o: 2两数相加.c
	$(CC) -c 2两数相加.c -o 2两数相加.o $(CFLAGS)
